import type { AnalysisReport } from '@/types/api'

/** Build the PR body markdown for a fix PR. */
export function buildPrBody(report: AnalysisReport): string {
  const fixedCount = report.findings.filter(
    (f) => f.resolution === 'accepted' || f.resolution === 'auto-fixed' || f.autoFixed,
  ).length

  const changes = report.findings
    .filter((f) => f.resolution === 'accepted' || f.resolution === 'auto-fixed' || f.autoFixed)
    .slice(0, 20)
    .map((f) => `- \`${f.operation ?? '—'}\` — ${f.rule}`)
    .join('\n')

  return `## ⚕ MCP Doctor — Spec improvements

This PR improves \`${report.spec.file}\` for MCP/LLM-agent usability.

- **${fixedCount}** change(s) applied
- OpenAPI ${report.spec.version}, MCP spec ${report.mcpSpecVersion}

### Changes

${changes || '_No changes applied._'}

---
🤖 Generated by [MCP Doctor](https://github.com/TykTechnologies/openapi-to-mcp-doctor)
`
}

export const DEFAULT_PR_TITLE = 'fix: improve OpenAPI spec for MCP readiness'
